import { Component } from '@angular/core';

@Component({
  selector: 'app-unpadded-frame',
  templateUrl: './unpadded-frame.component.html',
})
export class UnpaddedFrameComponent {
  // tslint:disable-next-line:max-line-length
  tableData = new Promise(resolve => setTimeout(() => resolve([{ firstName: 'fname1', lastName: 'lname1', age: 10, active: true, date: new Date('2020-04-18').toISOString() }, { firstName: 'fname2', lastName: null, age: 20, active: false }, { firstName: 'fname3', lastName: 'lname3', age: 20, active: null }, { firstName: 'fname1', lastName: 'lname1', age: 10, active: true }, { firstName: 'fname2', lastName: 'lname2', age: 20, active: false }, { firstName: 'fname3', lastName: 'Dies ist ein sehr langer Text.\nIch mache das nur zum testen. Jetzt kommt ein \\n um zu testen wie das Aussieht.\n\t\\t muss auch getestet werden.\n  Zwei leerzeichen sollten auch funktionieren.', age: 20, active: true }, { firstName: 'fname1', lastName: 'lname1', age: 10, active: true }, { firstName: 'fname2', lastName: 'lname2', age: 2, active: false, date: new Date('2018-04-18').toISOString() }, { firstName: 'fname2', lastName: 'lname2', age: 1, active: false, date: new Date('2019-04-18').toISOString() }, { firstName: 'fname3', lastName: 'lname3', age: 20, active: true }, { firstName: 'fname1', lastName: 'lname1', age: 10, active: true }, { firstName: 'fname2', lastName: 'lname2', age: 20, active: false }, { firstName: 'fname3', lastName: 'lname3', age: 20, active: true }, { firstName: 'fname1', lastName: undefined, age: 10, active: true }, { firstName: 'fname2', lastName: 'lname2', age: 20, active: false }, { firstName: 'fname2', lastName: 'lname2', age: null, active: false }, { firstName: 'fname3', lastName: 'lname3', age: 20, active: true }, { firstName: 'fname1', lastName: 'lname1', age: 10, active: true, date: new Date('2019-02-18').toISOString() }, { firstName: 'fname2', lastName: 'lname2', age: 20, active: false }, { firstName: 'fname3', lastName: 'lname3', age: 3, active: true }, { firstName: 'fname1', lastName: 'lname1', age: null, active: true, date: new Date('2019-04-20').toISOString() }, { firstName: undefined, lastName: 'lname2', age: 20, active: false }].map(r => Object.assign({}, r, { id: Math.random().toString(36).substr(2, 10) }))), 5000))
}
